import {
  UserProfile,
  BankAccount,
  CreditCard,
  CreditTransaction,
  FutureGoal,
  BankMonthlyData,
  OptionalExpense,
  UnplannedExpense,
} from '../types/finance';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Rohan Sharma',
  mobileNumber: '+91 98765 43210',
  currency: '₹',
  unplannedSpendingLimit: 18000,
};

export const INITIAL_BANKS: BankAccount[] = [
  {
    id: 'bank-hdfc-01',
    bankName: 'HDFC Bank',
    nickname: 'Salary Account',
    accountNumberMasked: '•••• 4092',
    color: '#004c8f',
    createdAt: '2026-01-01',
    plannedCategories: [
      { id: 'hdfc-cat-rent', category: 'House Rent', amountSet: 32000 },
      { id: 'hdfc-cat-grocery', category: 'Grocery & Supermarket', amountSet: 12000 },
      { id: 'hdfc-cat-sip', category: 'SIP & Mutual Funds', amountSet: 25000 },
      { id: 'hdfc-cat-electricity', category: 'Electricity & Utilities', amountSet: 4500 },
      { id: 'hdfc-cat-insurance', category: 'Term & Health Insurance', amountSet: 3500 },
      { id: 'hdfc-cat-fuel', category: 'Fuel & Commute', amountSet: 5000 },
      { id: 'hdfc-cat-mobile', category: 'Mobile & Broadband', amountSet: 2000 },
      { id: 'hdfc-cat-entertainment', category: 'Dining & Entertainment', amountSet: 6000 },
    ],
  },
  {
    id: 'bank-sbi-02',
    bankName: 'State Bank of India',
    nickname: 'Primary Savings',
    accountNumberMasked: '•••• 8124',
    color: '#280071',
    createdAt: '2026-01-01',
    plannedCategories: [
      { id: 'sbi-cat-emi', category: 'Home Loan EMI', amountSet: 22000 },
      { id: 'sbi-cat-family', category: 'Family Maintenance', amountSet: 15000 },
      { id: 'sbi-cat-medical', category: 'Parents Medical & Health', amountSet: 5000 },
      { id: 'sbi-cat-secondary-grocery', category: 'Local Provisions & Milk', amountSet: 3000 },
      { id: 'sbi-cat-emergency-sip', category: 'Contingency Liquid Fund', amountSet: 5000 },
    ],
  },
  {
    id: 'bank-icici-03',
    bankName: 'ICICI Bank',
    nickname: 'Wealth & Secondary',
    accountNumberMasked: '•••• 9541',
    color: '#b33a05',
    createdAt: '2026-01-01',
    plannedCategories: [
      { id: 'icici-cat-direct-equity', category: 'Direct Equity & Stocks', amountSet: 15000 },
      { id: 'icici-cat-ppf', category: 'PPF Contribution', amountSet: 10000 },
      { id: 'icici-cat-subscriptions', category: 'Software & Cloud Tools', amountSet: 3500 },
      { id: 'icici-cat-gym', category: 'Gym & Sports Club', amountSet: 2500 },
    ],
  },
];

export const INITIAL_CREDIT_CARDS: CreditCard[] = [
  {
    id: 'card-hdfc-regalia',
    cardName: 'HDFC Regalia Gold',
    issuer: 'HDFC Bank',
    nickname: 'Primary Travel & Dining Card',
    creditLimit: 350000,
    billingCycleStart: 12,
    billingCycleEnd: 11,
    cardColor: 'from-amber-700 via-amber-900 to-stone-950',
    lastPaymentDate: '2026-08-08',
    lastPaymentAmount: 48500,
    createdAt: '2026-01-01',
  },
  {
    id: 'card-icici-amazon',
    cardName: 'ICICI Amazon Pay',
    issuer: 'ICICI Bank',
    nickname: 'Cashback & Online Shopping',
    creditLimit: 200000,
    billingCycleStart: 20,
    billingCycleEnd: 19,
    cardColor: 'from-blue-700 via-slate-900 to-black',
    lastPaymentDate: '2026-08-16',
    lastPaymentAmount: 18200,
    createdAt: '2026-01-01',
  },
];

export const INITIAL_FUTURE_GOALS: FutureGoal[] = [
  {
    id: 'goal-goa-trip',
    goalName: 'Goa Annual Vacation',
    description: 'Beach resort stay, flight tickets, and local experiences for 4 days with family.',
    targetAmount: 85000,
    expectedExpenseDate: '2026-11-20',
    monthlyTarget: 15000,
    actualSaved: 55000,
    status: 'in_progress',
    isManualSuccess: false,
    createdAt: '2026-05-01',
    allocations: [
      {
        id: 'alloc-goa-1',
        type: 'monthly_saving',
        bankId: 'bank-hdfc-01',
        monthlyTarget: 10000,
        purpose: 'Direct monthly savings allocation',
        expectedExpenseDate: '2026-11-20',
      },
      {
        id: 'alloc-goa-2',
        type: 'planned_expense_cut',
        bankId: 'bank-sbi-02',
        plannedExpenseCategory: 'Local Provisions & Milk',
        monthlyReductionAmount: 1000,
        purpose: 'Redirect secondary grocery savings to trip',
        expectedExpenseDate: '2026-11-20',
      },
      {
        id: 'alloc-goa-3',
        type: 'planned_expense_cut',
        bankId: 'bank-hdfc-01',
        plannedExpenseCategory: 'Dining & Entertainment',
        monthlyReductionAmount: 4000,
        purpose: 'Cut back on weekend dining out',
        expectedExpenseDate: '2026-11-20',
      },
    ],
  },
  {
    id: 'goal-macbook-pro',
    goalName: 'MacBook Pro M3 Max',
    description: 'Upgrading work machine for app development and content editing.',
    targetAmount: 220000,
    expectedExpenseDate: '2027-01-15',
    monthlyTarget: 20000,
    actualSaved: 160000,
    status: 'in_progress',
    isManualSuccess: false,
    createdAt: '2026-03-01',
    allocations: [
      {
        id: 'alloc-mac-1',
        type: 'monthly_saving',
        bankId: 'bank-icici-03',
        monthlyTarget: 20000,
        purpose: 'Direct wealth transfer target',
        expectedExpenseDate: '2027-01-15',
      },
    ],
  },
  {
    id: 'goal-emergency-fund',
    goalName: '6-Month Emergency Runway',
    description: 'Target ₹5 Lakhs liquid reserve parked across safe deposits.',
    targetAmount: 500000,
    expectedExpenseDate: '2027-06-30',
    monthlyTarget: 25000,
    actualSaved: 380000,
    status: 'in_progress',
    isManualSuccess: false,
    createdAt: '2026-01-01',
    allocations: [
      {
        id: 'alloc-efund-1',
        type: 'monthly_saving',
        bankId: 'bank-sbi-02',
        monthlyTarget: 25000,
        purpose: 'Emergency savings reserve allocation',
        expectedExpenseDate: '2027-06-30',
      },
    ],
  },
];

export const INITIAL_MONTHLY_DATA: Record<string, Record<string, BankMonthlyData>> = {
  // 2026-08 (Current Active Month)
  '2026-08': {
    'bank-hdfc-01': {
      bankId: 'bank-hdfc-01',
      month: '2026-08',
      monthlyIncome: 145000,
      amountAtBank: 35000,
      plannedExpenseValues: {
        'hdfc-cat-rent': { amountSet: 32000, amountSpent: 32000 },
        'hdfc-cat-grocery': { amountSet: 12000, amountSpent: 11400 },
        'hdfc-cat-sip': { amountSet: 25000, amountSpent: 25000 },
        'hdfc-cat-electricity': { amountSet: 4500, amountSpent: 3850 },
        'hdfc-cat-insurance': { amountSet: 3500, amountSpent: 3500 },
        'hdfc-cat-fuel': { amountSet: 5000, amountSpent: 4200 },
        'hdfc-cat-mobile': { amountSet: 2000, amountSpent: 1999 },
        'hdfc-cat-entertainment': { amountSet: 6000, amountSpent: 4800 },
      },
      unplannedExpenseIds: ['unp-01', 'unp-02', 'unp-03'],
    },
    'bank-sbi-02': {
      bankId: 'bank-sbi-02',
      month: '2026-08',
      monthlyIncome: 35000,
      amountAtBank: 82000,
      plannedExpenseValues: {
        'sbi-cat-emi': { amountSet: 22000, amountSpent: 22000 },
        'sbi-cat-family': { amountSet: 15000, amountSpent: 15000 },
        'sbi-cat-medical': { amountSet: 5000, amountSpent: 3200 },
        'sbi-cat-secondary-grocery': { amountSet: 3000, amountSpent: 2800 },
        'sbi-cat-emergency-sip': { amountSet: 5000, amountSpent: 5000 },
      },
      unplannedExpenseIds: ['unp-04'],
    },
    'bank-icici-03': {
      bankId: 'bank-icici-03',
      month: '2026-08',
      monthlyIncome: 28000,
      amountAtBank: 115000,
      plannedExpenseValues: {
        'icici-cat-direct-equity': { amountSet: 15000, amountSpent: 15000 },
        'icici-cat-ppf': { amountSet: 10000, amountSpent: 10000 },
        'icici-cat-subscriptions': { amountSet: 3500, amountSpent: 2900 },
        'icici-cat-gym': { amountSet: 2500, amountSpent: 2500 },
      },
      unplannedExpenseIds: ['unp-05'],
    },
  },
  // 2026-07 (Previous Month History)
  '2026-07': {
    'bank-hdfc-01': {
      bankId: 'bank-hdfc-01',
      month: '2026-07',
      monthlyIncome: 145000,
      amountAtBank: 28000,
      plannedExpenseValues: {
        'hdfc-cat-rent': { amountSet: 32000, amountSpent: 32000 },
        'hdfc-cat-grocery': { amountSet: 12000, amountSpent: 12800 },
        'hdfc-cat-sip': { amountSet: 25000, amountSpent: 25000 },
        'hdfc-cat-electricity': { amountSet: 4500, amountSpent: 4900 },
        'hdfc-cat-insurance': { amountSet: 3500, amountSpent: 3500 },
        'hdfc-cat-fuel': { amountSet: 5000, amountSpent: 5100 },
        'hdfc-cat-mobile': { amountSet: 2000, amountSpent: 2000 },
        'hdfc-cat-entertainment': { amountSet: 6000, amountSpent: 6200 },
      },
      unplannedExpenseIds: ['unp-06', 'unp-07'],
    },
    'bank-sbi-02': {
      bankId: 'bank-sbi-02',
      month: '2026-07',
      monthlyIncome: 35000,
      amountAtBank: 75000,
      plannedExpenseValues: {
        'sbi-cat-emi': { amountSet: 22000, amountSpent: 22000 },
        'sbi-cat-family': { amountSet: 15000, amountSpent: 15000 },
        'sbi-cat-medical': { amountSet: 5000, amountSpent: 4500 },
        'sbi-cat-secondary-grocery': { amountSet: 3000, amountSpent: 2900 },
        'sbi-cat-emergency-sip': { amountSet: 5000, amountSpent: 5000 },
      },
      unplannedExpenseIds: [],
    },
    'bank-icici-03': {
      bankId: 'bank-icici-03',
      month: '2026-07',
      monthlyIncome: 25000,
      amountAtBank: 105000,
      plannedExpenseValues: {
        'icici-cat-direct-equity': { amountSet: 15000, amountSpent: 15000 },
        'icici-cat-ppf': { amountSet: 10000, amountSpent: 10000 },
        'icici-cat-subscriptions': { amountSet: 3500, amountSpent: 3500 },
        'icici-cat-gym': { amountSet: 2500, amountSpent: 2500 },
      },
      unplannedExpenseIds: [],
    },
  },
};

export const INITIAL_UNPLANNED_EXPENSES: UnplannedExpense[] = [
  {
    id: 'unp-01',
    bankId: 'bank-hdfc-01',
    month: '2026-08',
    day: 5,
    fullDate: '5 August 2026',
    description: 'Vehicle tire replacement & puncture fix',
    amount: 4200,
    notes: 'Front right tire had sidewall leak during highway commute',
    createdAt: '2026-08-05',
  },
  {
    id: 'unp-02',
    bankId: 'bank-hdfc-01',
    month: '2026-08',
    day: 14,
    fullDate: '14 August 2026',
    description: 'Birthday celebration gift for colleague',
    amount: 2500,
    notes: 'Team contribution and gift card',
    createdAt: '2026-08-14',
  },
  {
    id: 'unp-03',
    bankId: 'bank-hdfc-01',
    month: '2026-08',
    day: 18,
    fullDate: '18 August 2026',
    description: 'Plumbing leak urgent repair',
    amount: 1850,
    notes: 'Kitchen sink connector pipe burst',
    createdAt: '2026-08-18',
  },
  {
    id: 'unp-04',
    bankId: 'bank-sbi-02',
    month: '2026-08',
    day: 10,
    fullDate: '10 August 2026',
    description: 'Specialist dental consultation & x-ray',
    amount: 3200,
    notes: 'Routine checkup and filling',
    createdAt: '2026-08-10',
  },
  {
    id: 'unp-05',
    bankId: 'bank-icici-03',
    month: '2026-08',
    day: 12,
    fullDate: '12 August 2026',
    description: 'Annual domain renewal & DNS server fee',
    amount: 1600,
    notes: 'Personal portfolio server infrastructure',
    createdAt: '2026-08-12',
  },
  {
    id: 'unp-06',
    bankId: 'bank-hdfc-01',
    month: '2026-07',
    day: 11,
    fullDate: '11 July 2026',
    description: 'Raincoat & monsoon umbrella pair',
    amount: 2100,
    notes: 'Monsoon preparation gear',
    createdAt: '2026-07-11',
  },
  {
    id: 'unp-07',
    bankId: 'bank-hdfc-01',
    month: '2026-07',
    day: 22,
    fullDate: '22 July 2026',
    description: 'AC gas top-up & filter servicing',
    amount: 3400,
    notes: 'Master bedroom AC maintenance',
    createdAt: '2026-07-22',
  },
];

export const INITIAL_CREDIT_TRANSACTIONS: CreditTransaction[] = [
  {
    id: 'ctx-01',
    cardId: 'card-hdfc-regalia',
    month: '2026-08',
    date: '2026-08-13',
    day: 13,
    category: 'Travel / Flights',
    description: 'Goa round-trip advance flight booking (2 Pax)',
    amount: 18400,
    expenseType: 'non_essential',
    createdAt: '2026-08-13',
  },
  {
    id: 'ctx-02',
    cardId: 'card-hdfc-regalia',
    month: '2026-08',
    date: '2026-08-15',
    day: 15,
    category: 'Dining',
    description: 'Independence Day family dinner at Olive Bistro',
    amount: 4800,
    expenseType: 'non_essential',
    createdAt: '2026-08-15',
  },
  {
    id: 'ctx-03',
    cardId: 'card-hdfc-regalia',
    month: '2026-08',
    date: '2026-08-17',
    day: 17,
    category: 'Groceries / Gourmet',
    description: 'Nature Basket imported supplies',
    amount: 3200,
    expenseType: 'essential',
    createdAt: '2026-08-17',
  },
  {
    id: 'ctx-04',
    cardId: 'card-hdfc-regalia',
    month: '2026-08',
    date: '2026-08-20',
    day: 20,
    category: 'Fuel',
    description: 'Indian Oil XP95 tank refill',
    amount: 4100,
    expenseType: 'essential',
    createdAt: '2026-08-20',
  },
  {
    id: 'ctx-05',
    cardId: 'card-icici-amazon',
    month: '2026-08',
    date: '2026-08-08',
    day: 8,
    category: 'Electronics',
    description: 'Ergonomic mechanical keyboard & desk mat',
    amount: 8900,
    expenseType: 'non_essential',
    createdAt: '2026-08-08',
  },
  {
    id: 'ctx-06',
    cardId: 'card-icici-amazon',
    month: '2026-08',
    date: '2026-08-12',
    day: 12,
    category: 'Pharmacy',
    description: 'Apollo Pharmacy monthly vitamins & essentials',
    amount: 2400,
    expenseType: 'essential',
    createdAt: '2026-08-12',
  },
  {
    id: 'ctx-07',
    cardId: 'card-icici-amazon',
    month: '2026-08',
    date: '2026-08-19',
    day: 19,
    category: 'Home & Kitchen',
    description: 'Water purifier replacement cartridge set',
    amount: 3100,
    expenseType: 'essential',
    createdAt: '2026-08-19',
  },
];

export const INITIAL_OPTIONAL_EXPENSES: OptionalExpense[] = [
  {
    id: 'opt-hdfc-01',
    bankId: 'bank-hdfc-01',
    month: '2026-08',
    title: 'Car Insurance Annual Renewal',
    amountSet: 14500,
    amountSpent: 14500,
    dueDate: '2026-08-28',
    notes: 'Comprehensive zero-dep vehicle policy renewal',
    isPaid: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'opt-sbi-02',
    bankId: 'bank-sbi-02',
    month: '2026-08',
    title: 'Quarterly Society Maintenance Cess',
    amountSet: 6000,
    amountSpent: 6000,
    dueDate: '2026-08-15',
    notes: 'Q3 society building paint & repair cess',
    isPaid: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'opt-icici-03',
    bankId: 'bank-icici-03',
    month: '2026-08',
    title: 'Annual Tech Domain & Server Renewals',
    amountSet: 4500,
    amountSpent: 4500,
    dueDate: '2026-08-20',
    notes: 'Cloud hosting & domain portfolio annual payment',
    isPaid: true,
    createdAt: '2026-08-01',
  },
];

